More checks.

diff --git a/bin/deployForIntegrationTest b/bin/deployForIntegrationTest
--- a/bin/deployForIntegrationTest
+++ b/bin/deployForIntegrationTest
@@ -13,6 +13,36 @@ then
 fi
 pushd $HOME/workspaces/inheritsource-develop/pawap/bin 
 
+
+# Check some dependencies 
+POSTGRESSERVICE=/etc/init.d/postgresql
+if [ ! -f ${POSTGRESSERVICE} ]; then 
+  echo "Missing postgresql script. Not installed?" 
+   exit 1;
+fi
+
+response=$(${POSTGRESSERVICE} status)
+if [[ ${response} != "Running clusters"* ]]
+then
+  echo "Postgres not running?"
+  exit 1
+fi
+
+APACHE2SERVICE=/etc/init.d/apache2
+if [ ! -f ${APACHE2SERVICE} ]; then 
+  echo "Missing apache2 script. Not installed?" 
+   exit 1;
+fi
+response=$(${APACHE2SERVICE} status)
+if [[ ${response} != "Apache2 is running"* ]]
+then
+  echo "Apache2 not running?"
+  exit 1
+fi
+
+
+
+
 # update from git 
 git pull
 if [ $? != 0 ]
